logging:
  level:
    org.apache.commons.httpclient.wire.content: info
    org.apache.commons.httpclient: info
    org.apache.commons.httpclient.wire.header: info

spring:
  profiles:
    active: dev
  application:
    name: demo
  thymeleaf:
    prefix: classpath:/templates/
  service:
    url: http://127.0.0.1:50005
  redis:
    host: 172.16.183.215
    port: 6379
    #password: 123456
    database: 9
    jedis:
      pool:
        max-active: 8
        max-wait: 3ms
        min-idle: 0
        max-idle: 8
  data:
    elasticsearch:
      cluster-name: elasticsearch
      #节点的地址，api模式端口号9300，千万不要写成9200
      cluster-nodes: 172.16.183.215:9300
      #开启本地缓存
      repositories: true



---
#dev env
spring:
  profiles: dev
server:
  port: 50005

---
#self env
spring:
  profiles: self
server:
  port: 50006

---
#beta env
spring:
  profiles: beta
server:
  port: 50007
chitchat:
---
#prod env
spring:
  profiles: prod
server:
  port: 50008
